name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Step
        run: echo "This job will be run first."

  fanout1:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - name: Fanout1 Step
        run: echo "This job will run after the initial job, in parallel with fanout2."

  fanout2:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - name: Fanout2 Step
        run: echo "This job will run after the initial job, in parallel with fanout1."

  fanin:
    runs-on: ubuntu-latest
    needs: [fanout1, fanout2]
    steps:
      - name: Fanin Step
        run: echo "This job will run after fanout1 and fanout2 have finished."

  conditional:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Step
        run: echo "This step runs with str equals 'ABC' and num equals 123"
        if: ${{ env.str == 'ABC' && env.num == 123 }}

  sequence:
    runs-on: ubuntu-latest
    steps:
      - name: Sequence Step
        run: echo "This step runs in sequence."

  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: Run Command Step
        run: echo "This step runs a command."
      
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Run Python script
        run: python script.py
